### ISSUE TITLE
[Bug]:您好！添加用户的cookie在6个小时左右就失效了，如何保存的时间更长一点？

### ISSUE THREAD

**Issue by KeFan999** [johlanse/study_xxqg#143]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v1.0.38-SNAPSHOT-1de1c28

### 运行环境

Debian

### 运行架构

AMD64

### 运行方式

Docker

### 重现步骤

[2022-11-07 15:00:00] [33m[warn] [0m开始尝试使用模板消息发送
[2022-11-07 15:00:00] [33m[warn] [0mXXX的cookie已失效
[2022-11-07 15:00:00] [36m[info] [0m开始执行保活任务

### 期望的结果是什么？

cookie保存的时间更长一点

### 实际的结果是什么？

6小时失效了

### docker运行命令或者docker-compose的内容

```golang
docker run --name study_xxqg --restart always -d -p 8080:8080 -v /etc/study_xxqg/:/opt/config/  jolanse/study_xxqg:latest
```

### 日志记录（可选）

```golang
[2022-11-07 15:00:00] [33m[warn] [0m开始尝试使用模板消息发送
[2022-11-07 15:00:00] [33m[warn] [0mXXX的cookie已失效
[2022-11-07 15:00:00] [36m[info] [0m开始执行保活任务
```

### 配置信息（可选）

```yaml
wechat:
  # 是否启用
  enable: true
  # 开发者平台设置的token
  token: "skTN7mQH7mBEQA1XGhSdXS部分"
  # 开发者平台的secret
  secret: "37d84d67b90a1c5a70部分"
  # 开发者平台的appId
  app_id: "wxac1e39fc1部分"
  # 发送登录消息需要使用的消息模板
  # 模板标题，随意  模板内容：  点我登录，然后在浏览器中打开！！
  login_temp_id: "07vzQ5-4TOOjtDy4_部分"
  # 发送普通消息需要使用的消息模板
  # 模板标题：随意 模板内容： {{data.DATA}}
  normal_temp_id: "部分qE9ojnIkIK4g9sFDAunfuvmNI4"
  # xxqg会每隔两小时左右检查所有用户的ck有效性，若开启该选项，会在检查失败时推送提醒消息
  push_login_warn: true
  # 微信管理员的openid,可点击关于按钮获得，配置后请重启程序
  super_open_id: "owc5U6HuEf部分"
```
